services:
  # ---------- MODE DEV ----------
  cookeys-dev:
    profiles: [ "dev" ]
    container_name: cookeys-dev
    build:
      context: .
      target: build          # on reste sur le stage build (Node 14 + code)
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app               # Code du projet
      - /app/node_modules    # Préserve les dépendances NPM
    environment:
      - NODE_ENV=development

  # ---------- MODE PROD ----------
  cookeys:
    profiles: [ "prod" ]
    container_name: cookeys-prod
    build:
      context: .
      target: prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

  # ---------- MODE APP ----------
  cookeys-app:
    profiles: [ "app" ]
    container_name: cookeys-app
    build:
      context: .
      target: electron-build
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: "yarn electron:package"

  cookeys-tauri-linux:
    profiles: [ "app-tauri" ]
    container_name: cookeys-tauri-linux
    build:
      context: .
      dockerfile: Dockerfile
      target: tauri
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn tauri build --target x86_64-unknown-linux-gnu

  cookeys-tauri-windows:
    profiles: [ "app-tauri" ]
    container_name: cookeys-tauri-windows
    build:
      context: .
      dockerfile: Dockerfile
      target: tauri
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # optionnel : variables pour Wine / Locale
      - WINEDEBUG=-all
    command: yarn tauri build --target x86_64-pc-windows-gnu
