services:
  cookeys:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules # éviter que node_modules local n'écrase celui du conteneur
    environment:
      - NODE_ENV=development
